name: game_one
description: Game for MoCIoT

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flame: ^0.10.2
  scoped_model: ^1.0.1
  cupertino_icons: ^0.1.2
  shared_preferences: ^0.5.1+2
  card_settings: ^1.4.1
  flutter_blue: ^0.5.0
  vector_math: ^2.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

flutter:
  uses-material-design: true
  assets:
    - assets/images/flame.png
    - assets/images/explosion.png
    - assets/images/ground.png
    - assets/images/wall-L.png
    - assets/images/wall-R.png
    - assets/images/wall-U.png
    - assets/images/wall-D.png
    - assets/images/edge-BL.png
    - assets/images/edge-BR.png
    - assets/images/edge-TL.png
    - assets/images/edge-TR.png
    - assets/images/corner-BL.png
    - assets/images/corner-BR.png
    - assets/images/corner-TL.png
    - assets/images/corner-TR.png
    - assets/images/block.png
    - assets/images/death-screen-10.png
    - assets/images/death-screen-20.png
    - assets/images/death-screen-30.png
    - assets/images/death-screen-40.png
    - assets/images/death-screen-50.png
    - assets/images/death-screen-60.png
    - assets/images/death-screen-70.png
    - assets/images/death-screen-80.png
    - assets/images/death-screen-90.png
    - assets/images/death-screen-100.png
    - assets/images/restart.png
    - assets/images/start.png
    - assets/images/pause.png
    - assets/images/cogwheel.png

